### ISSUE TITLE
MacOS, installation isse

### ISSUE THREAD

**Issue by chodar89** [TeoZosa/structlog-sentry-logger#511]
Hi, guys. I have trouble installing the package on macOS. It seems to be a problem only on my machine as my colleagues don't experience that issue. A few details of the environment are below:
 - MacBook Pro (14-inch, 2021)
 - MacOS - 12.3.1
 - Apple M1 Pro
 - Python 3.10.0

The log for (structlog-sentry-logger==0.15.0):
```
Building wheels for collected packages: structlog-sentry-logger
  Building wheel for structlog-sentry-logger (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for structlog-sentry-logger (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      A setup.py file already exists. Using it.
      running build
      running build_py
      creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310
      creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      copying structlog_sentry_logger/__init__.py -> /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      copying structlog_sentry_logger/_feature_flags.py -> /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      copying structlog_sentry_logger/structlog_sentry.py -> /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      copying structlog_sentry_logger/_config.py -> /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      copying structlog_sentry_logger/py.typed -> /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/lib.macosx-12.2-arm64-cpython-310/structlog_sentry_logger
      running build_ext
      building '451ad3e1dda0bf230bf3__mypyc' extension
      creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310
      creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310/build
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/mypyc/lib-rt -Ibuild -I/Users/tobiasz/Repositories/cat-app/.venv/include -I/Users/tobiasz/.pyenv/versions/3.10.0/include/python3.10 -c build/__native_451ad3e1dda0bf230bf3.c -o /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310/build/__native_451ad3e1dda0bf230bf3.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option
      build/__native_451ad3e1dda0bf230bf3.c:2722:10: error: variable 'cpy_r_r34' set but not used [-Werror,-Wunused-but-set-variable]
          char cpy_r_r34;
               ^
      build/__native_451ad3e1dda0bf230bf3.c:11071:15: error: variable 'cpy_r_r312' set but not used [-Werror,-Wunused-but-set-variable]
          PyObject *cpy_r_r312;
                    ^
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      Traceback (most recent call last):
        File "/Users/tobiasz/Repositories/cat-app/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/tobiasz/Repositories/cat-app/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tobiasz/Repositories/cat-app/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
          return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
        File "/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 78, in make_in
          wb.build()
        File "/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 110, in build
          self._build(zip_file)
        File "/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 162, in _build
          self._run_build_command(setup)
        File "/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 190, in _run_build_command
          subprocess.check_call(
        File "/Users/tobiasz/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/tobiasz/Repositories/cat-app/.venv/bin/python', '/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/setup.py', 'build', '-b', '/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for structlog-sentry-logger
Failed to build structlog-sentry-logger
ERROR: Could not build wheels for structlog-sentry-logger, which is required to install pyproject.toml-based projects
```

Version ==0.17.4 

```
      build/__native_451ad3e1dda0bf230bf3.c:2663:10: error: variable 'cpy_r_r39' set but not used [-Werror,-Wunused-but-set-variable]
          char cpy_r_r39;
               ^
      build/__native_451ad3e1dda0bf230bf3.c:11135:15: error: variable 'cpy_r_r312' set but not used [-Werror,-Wunused-but-set-variable]
          PyObject *cpy_r_r312;
```

This is a comparison between the last version that I can install (0.9.0). It looks that c_library breaks this. 
https://github.com/TeoZosa/structlog-sentry-logger/compare/0.9.0...0.9.1

**Comment by TeoZosa** [comment]
Hey @chodar89 & @ivanrvpereira, sorry for missing this, I was in the middle of moving to a new country the past few months so this issue somehow fell through the cracks.

It looks like the issue was, because there are only non-`arm64` pre-built wheels on PyPI at the moment, installing the library on Apple silicon attempts to compile the C library from scratch. If this occurs with a Clang compiler version >= 13 (due to [Clang 13 adding the `-Wunused-but-set-variable` compiler flag](https://releases.llvm.org/13.0.0/tools/clang/docs/ReleaseNotes.html#:~:text=Wunused%2Dbut%2Dset%2Dparameter%20and%20%2DWunused%2Dbut%2Dset%2Dvariable%20emit%20warnings%20when%20a%20parameter%20or%20a%20variable%20is%20set%20but%20not%20used.)), compilation will fail with the posted output. 

This _should_ be fixed in #615. Once that's merged I can cut a new release.

**Comment by TeoZosa** [comment]
For anyone reading this that needs compatibility with older versions, you can also manually add `CFLAGS="-Wno-unused-but-set-variable"` to your env variables prior to running the install command. e.g.,

```shell
env CFLAGS="-Wno-unused-but-set-variable" pip install structlog-sentry-logger
```
